
services:
    alist:
        image: 'xhofe/alist:latest'
        container_name: alist
        volumes:
            - './alist:/opt/alist/data'
        ports:
            - '${ALIST_WEBUI_PORT}:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        restart: unless-stopped
